spring.application.name=tko11-lms

# データベースの接続URL（localhostとポート、DB名を環境に合わせて変更）
spring.datasource.url=jdbc:postgresql://localhost:5432/bookdb
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
# PostgreSQL用のドライバクラス指定
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernateの自動テーブル作成設定（開発時はupdate、本番はnone推奨）
spring.jpa.hibernate.ddl-auto=update

# 実行されるSQLをコンソールに出力する設定
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 任意のファイル名・パスを指定して保存する場合
logging.file.name=logs/myapp.log

# 全体の基本ログレベルを WARN 以上にする（ノイズを減らす）
logging.level.root=info