spring.application.name=tko11-lms

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://10.0.2.89:5432/appdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tko11admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# 任意のファイル名・パスを指定して保存する場合
logging.file.name=logs/appserver.log

# 全体の基本ログレベルを WARN 以上にする（ノイズを減らす）
logging.level.root=info