spring.application.name=tko11-lms

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tko11admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# 実際に発行されたSQL文をコンソールに表示する
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQLに渡されたパラメータ（社員番号やパスワードなど）の値を表示する
logging.level.org.hibernate.orm.jdbc.bind=trace

# 二人作業のためポート被りを回避(以下設定がない場合は8080)
server.port=8081